import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1120,height:850}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:5173');
  await page.locator('#play').click();
  await page.locator('#export-resolution').click();
  await page.getByRole('option',{name:'4K · 3840 × 2160',exact:true}).click();
  await page.locator('#export').click();
  await expect(page.locator('#export-overlay')).toBeVisible();
  await expect(page.locator('.export-job-format')).toContainText('3840 × 2160 · 12 FPS');
  const stage=await page.locator('#stage').boundingBox(),card=await page.locator('.stage-export-card').boundingBox();
  assert.ok(Math.abs(stage.x+stage.width/2-card.x-card.width/2)<2);
  assert.ok(Math.abs(stage.y+stage.height/2-card.y-card.height/2)<2);
  await page.locator('.thought-line__head').click();
  await expect(page.locator('.thought-line__head')).toHaveAttribute('aria-expanded','false');
  await page.locator('.thought-line__head').click();
  await page.screenshot({path:'test-results/export-overlay-desktop.png'});
  await page.locator('#cancel-export').click();
  await expect(page.locator('.export-job-result')).toContainText('未生成视频文件');
  await expect(page.locator('.thought-line__text--done')).toHaveText('已取消，用时');
  await page.locator('#dismiss-export').click();
  await expect(page.locator('#export-overlay')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#export').click();
  await expect(page.locator('.export-job-format')).toContainText('3840 × 2160');
  await page.screenshot({path:'test-results/export-overlay-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const mobileStage=await page.locator('#stage').boundingBox(),mobileCard=await page.locator('.stage-export-card').boundingBox();
  assert.ok(mobileCard.x>=mobileStage.x&&mobileCard.x+mobileCard.width<=mobileStage.x+mobileStage.width);
  assert.ok(mobileCard.y>=mobileStage.y&&mobileCard.y+mobileCard.height<=mobileStage.y+mobileStage.height);
  await page.locator('#cancel-export').click();
  await expect(page.locator('#dismiss-export')).toBeVisible();
  await page.locator('#dismiss-export').click();
  await page.locator('#range-end').press('Home');
  const download=page.waitForEvent('download');
  await page.locator('#export').click();await download;
  await expect(page.locator('.thought-line__text--done')).toHaveText('导出完成，用时');
  await expect(page.locator('.export-job-result')).toContainText('下载已开始');
  await expect(page.locator('.thought-line__head')).toHaveAttribute('aria-expanded','false');
  await page.locator('.thought-line__head').click();
  await expect(page.locator('.thought-line__steps')).toContainText('封装 MP4 文件');
  assert.deepEqual(errors,[]);
  const failed=await browser.newPage({reducedMotion:'reduce'});
  await failed.addInitScript(()=>{VideoEncoder.isConfigSupported=async()=>({supported:false});});
  await failed.goto('http://localhost:5173');await failed.locator('#export').click();
  await expect(failed.locator('.thought-line__text--done')).toHaveText('导出失败，用时');
  await expect(failed.locator('.export-job-result')).toContainText('不支持');
  await failed.locator('#dismiss-export').click();
  console.log('PASS: centered ThoughtLine, descriptions, collapsible steps, cancellation, completion, failure, and mobile layout.');
}finally{await browser.close();}
