import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('test-results', { recursive:true });
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function sliderTo(name, steps) {
  const input=page.getByRole('slider',{name,exact:true});
  await input.focus();await input.press('Home');
  for(let i=0;i<steps;i++)await input.press('ArrowRight');
}
await page.goto('http://localhost:5173');
await page.locator('#stage canvas').waitFor();
await page.waitForTimeout(1800);
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
console.log('Preview rendered');
await page.locator('#play').click();
const first=await page.locator('#seek').inputValue();
await page.waitForTimeout(250);
assert.equal(await page.locator('#seek').inputValue(),first,'Pause freezes playhead');
await page.locator('#next').click();
assert.ok(Number(await page.locator('#seek').inputValue())>Number(first),'Next advances');
await sliderTo('豆子高度',7);
assert.equal(await page.locator('#height-value').textContent(),'1.4× 高度');
const motion=page.getByRole('switch',{name:'逐颗换豆',exact:true});
await motion.click();assert.equal(await motion.getAttribute('aria-checked'),'false');
await motion.focus();await motion.press('Space');
assert.equal(await motion.getAttribute('aria-checked'),'true');
assert.match(await page.locator('#play').getAttribute('aria-label'),/播放/,'Switch keyboard action must not toggle playback');
await page.locator('#stage canvas').hover();await page.mouse.wheel(0,-1600);await page.waitForTimeout(600);
await page.locator('#stage').screenshot({path:'test-results/bead-detail.png'});
await page.locator('#reset-view').click();
await sliderTo('豆子高度',3);
await sliderTo('画面密度',3);
assert.equal(await page.locator('#bead-count').textContent(),'14,400 颗拼豆');
for(const fps of [6,12,30,24]){await page.locator('#fps').click();await page.getByRole('option',{name:fps===6?'6 FPS · 定格':`${fps} FPS`,exact:true}).click();assert.equal(await page.locator('#stage-fps').textContent(),`${fps} FPS`);}
await page.locator('#palette [data-value="original"]').click();
assert.equal(await page.locator('#palette-note').textContent(),'全彩');
await page.locator('#palette [data-value="beads"]').click();
assert.equal(await page.locator('#palette-note').textContent(),'32 色');
await page.locator('#view [data-value="3d"]').click();
assert.match(await page.locator('#view-hint').textContent(),/拖拽旋转/);
await page.getByRole('switch',{name:'塑料质感',exact:true}).click();
console.log('Playback and settings passed');
const pngPromise=page.waitForEvent('download');await page.locator('#snapshot').click();const png=await pngPromise;assert.match(png.suggestedFilename(),/\.png$/);await png.saveAs('test-results/frame.png');
await sliderTo('画面密度',0);
const fixturePage=await browser.newPage();
await fixturePage.goto('http://localhost:5173/index.html?fixture');
await fixturePage.goto('about:blank');
const fixture=await fixturePage.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=90;document.body.append(canvas);const c=canvas.getContext('2d');c.fillStyle='#48799e';c.fillRect(0,0,160,90);const stream=canvas.captureStream(0);const track=stream.getVideoTracks()[0];const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];const finished=new Promise(resolve=>{recorder.onstop=async()=>{const data=new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer());resolve(Array.from(data));};});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();let n=0;const timer=setInterval(()=>{c.fillStyle=n%2?'#e9bb68':'#48799e';c.fillRect(0,0,160,90);c.fillStyle='#ffffff';c.fillRect(n*5%140,20,20,30);track.requestFrame();n++;if(n===18){clearInterval(timer);setTimeout(()=>{recorder.stop();stream.getTracks().forEach(t=>t.stop());},150);}},84);return finished;});
await fixturePage.close();
await writeFile('test-results/fixture.webm',Buffer.from(fixture));
console.log('Fixture generated',fixture.length);
await page.locator('#file').setInputFiles('test-results/fixture.webm');
await page.waitForFunction(()=>document.getElementById('source-name').textContent==='fixture.webm');
await page.waitForTimeout(700);
console.log('Video imported');
assert.match(await page.locator('#source-meta').textContent(),/160 × 90/);
const exportPromise=page.waitForEvent('download',{timeout:30000});await page.locator('#export').click();assert.equal(await page.locator('#fps').isDisabled(),true,'Appica controls lock during encoding');const exported=await exportPromise;assert.match(exported.suggestedFilename(),/\.(mp4|webm)$/);await exported.saveAs(`test-results/smoke-export.${exported.suggestedFilename().endsWith('.mp4')?'mp4':'webm'}`);
await page.locator('#demo').click();await page.locator('#view [data-value="front"]').click();
await page.locator('#help').click();assert.equal(await page.getByRole('dialog').isVisible(),true);await page.getByRole('button',{name:'关闭指南'}).click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await page.screenshot({path:'test-results/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');
assert.deepEqual(errors,[],'No browser runtime errors');
console.log('PASS: playback, stepping, bead height, replacement toggle, close-up camera, density, palette, texture, PNG, local video import, offline video export, help, mobile layout; no runtime errors.');
await browser.close();
